from pathlib import Path

from authrift.models import Finding, ScanResult
from authrift.utils.redact import redact_response_body


def finding_to_markdown(finding: Finding, include_raw_evidence: bool = False) -> str:
    lines = [
        f"# {finding.finding_id}",
        "",
        "## Potential Authorization Issue",
        "",
        f"**Type:** {finding.mutation_type.value}",
        f"**Endpoint:** {finding.method.value} {finding.endpoint}",
        f"**Confidence:** {finding.confidence.value} ({finding.score}/100)",
        "",
        "## Baseline",
        "",
        f"- Actor: {finding.baseline_actor}",
        f"- Status: {finding.baseline_response.status_code}",
        f"- Content-Type: {finding.baseline_response.content_type or 'N/A'}",
        "",
        "## Authorization Test",
        "",
        f"- Actor: {finding.test_actor}",
        f"- Status: {finding.test_response.status_code}",
        "",
        "## Differential Analysis",
        "",
        f"- Body similarity: {finding.diff.body_similarity:.1%}",
    ]

    if finding.diff.json_structure_similarity is not None:
        lines.append(
            f"- JSON structural similarity: {finding.diff.json_structure_similarity:.1%}"
        )
    else:
        lines.append("- JSON structural similarity: N/A (non-JSON response)")

    lines.extend([
        f"- Status match: {finding.diff.status_match}",
        f"- Content length difference: {finding.diff.content_length_diff} bytes",
        "",
    ])

    if finding.diff.sensitive_fields_in_response:
        lines.append("### Sensitive Fields Detected")
        lines.append("")
        for field in finding.diff.sensitive_fields_in_response:
            lines.append(f"- `{field}`")
        lines.append("")

    lines.append("### Scoring Signals")
    lines.append("")
    lines.append("| Signal | Points |")
    lines.append("|--------|--------|")
    for signal in finding.signals:
        sign = "+" if signal.points >= 0 else ""
        lines.append(f"| {signal.description} | {sign}{signal.points} |")
    lines.append("")

    baseline_body_disp = (
        finding.baseline_response.body
        if include_raw_evidence
        else redact_response_body(finding.baseline_response.body)
    )
    test_body_disp = (
        finding.test_response.body
        if include_raw_evidence
        else redact_response_body(finding.test_response.body)
    )

    if baseline_body_disp or test_body_disp:
        lines.extend([
            "## Evidence",
            "",
            f"### Baseline Response ({finding.baseline_actor})",
            "```json" if "json" in (finding.baseline_response.content_type or "") else "```",
            baseline_body_disp[:1500] if baseline_body_disp else "(empty)",
            "```",
            "",
            f"### Test Response ({finding.test_actor})",
            "```json" if "json" in (finding.test_response.content_type or "") else "```",
            test_body_disp[:1500] if test_body_disp else "(empty)",
            "```",
            "",
        ])

    lines.extend([
        "## Assessment",
        "",
        f"Potential {finding.mutation_type.value.lower().replace('_', ' ')} authorization failure.",
        "",
        "**Manual verification required.**",
        "",
        "---",
        f"*Generated by AUTHRIFT v0.1.0 at {finding.timestamp.isoformat()}*",
    ])

    return "
".join(lines)


def summary_to_markdown(result: ScanResult) -> str:
    lines = [
        "# AUTHRIFT Scan Summary",
        "",
        f"- Imported requests processed: {result.imported_requests_processed or result.total_requests}",
        f"- HTTP requests sent: {result.http_requests_sent}",
        f"- Mutations completed: {result.mutations_completed or result.total_mutations}",
        f"- Skipped (unsafe methods): {result.skipped_unsafe}",
        f"- Findings: {len(result.findings)}",
        f"- Errors: {len(result.errors)}",
        f"- Started: {result.started_at.isoformat()}",
    ]

    if result.completed_at:
        lines.append(f"- Completed: {result.completed_at.isoformat()}")

    lines.append("")

    if result.findings:
        lines.extend([
            "## Findings",
            "",
            "| ID | Endpoint | Type | Baseline Actor | Test Actor | Confidence | Score |",
            "|----|----------|------|----------------|------------|------------|-------|",
        ])
        for f in result.findings:
            lines.append(
                f"| {f.finding_id} | {f.method.value} {f.endpoint} "
                f"| {f.mutation_type.value} | {f.baseline_actor} | {f.test_actor} "
                f"| {f.confidence.value} | {f.score} |"
            )
        lines.append("")
    else:
        lines.extend(["## Findings", "", "No potential authorization issues detected.", ""])

    if result.errors:
        lines.extend(["## Errors", ""])
        for err in result.errors:
            lines.append(f"- {err}")
        lines.append("")

    lines.extend([
        "---",
        "*Generated by AUTHRIFT v0.1.0*",
    ])

    return "
".join(lines)


def write_reports(
    result: ScanResult,
    output_dir: str = "reports",
    include_raw_evidence: bool = False,
) -> list[Path]:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    summary_path = out / "summary.md"
    summary_path.write_text(summary_to_markdown(result))
    written.append(summary_path)

    for finding in result.findings:
        fpath = out / f"{finding.finding_id}.md"
        fpath.write_text(finding_to_markdown(finding, include_raw_evidence=include_raw_evidence))
        written.append(fpath)

    return written
